project:
  type: website

website:
  title: "Jonathan Kitt"
  site-url: "https://jonathankitt.netlify.app/"
  description: "My personal blog about coding with R"
  navbar:
    left: 
      - icon: rss
        href: blog.xml
      - icon: envelope
        href: mailto:jonathan.kitt@proton.me
      - icon: github
        href: https://github.com/KittJonathan
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-kitt/
      - icon: twitter
        href: https://twitter.com/KittJonathan
      - icon: mastodon
        href: https://fosstodon.org/@jonathankitt
    right:
      - text: Blog
        href: blog.qmd
      - text: Links
        href: links.qmd
format:
  html:
    theme:
      light: sandstone
      dark: darkly
    css: styles.css



